#!/bin/bash
bat_100=
bat_75=
bat_50=
bat_25=
bat_0=
ACPI=$(acpi)
percent=$(echo $ACPI | awk '{print $4}' | sed 's/[,%]//g')
status=$(echo $ACPI | awk '{ s = ""; for (i = 3; i <= NF; i++) s = s $i " "; print s }')
case $BLOCK_BUTTON in
#1|3) notify-send  "Battery" "$(acpi | awk '{print $5}' | sed 's/:..$//g') remaining" -t 2500 ;;
1|3) notify-send "Battery" "$status";;
esac
if [ $percent -lt 10 ]
then
	echo $bat_0 $percent%
elif [ $percent -lt 25 ]
then
	echo $bat_25 $percent%
elif [ $percent -lt 50 ]
then
	echo $bat_50 $percent%
elif [ $percent -lt 75 ]
then
	echo $bat_75 $percent%
elif [ $percent -lt 100 ]
then
	echo $bat_100 $percent%
fi
