format = """
$directory\
$git_branch\
(${custom.tiny_git_status}$git_status )\
$kubernetes\
$character\
"""

add_newline = false

[line_break]
disabled = true

[kubernetes]
disabled=false
format = '[$symbol]($style)'
contexts = [
  { context_pattern = "[^p].*", symbol = "" },
  { context_pattern = "prod", symbol = "\\[prod k8s\\] ", style = "bold red" }
]

[directory]
style = "bold blue" # rose pine moon
# style = "bold cyan" # original
truncation_length = 3
truncate_to_repo = true
# fish_style_pwd_dir_length = 1

[character]
# optional symbol ♪ ›
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
# vimcmd_symbol = "[>](bold purple)"

[git_branch]
format = "[$branch]($style) "
style = "bold purple" # rose pine moon
#style = "bold blue" # original

[custom.tiny_git_status]
format = '[$symbol]($style)'
style = 'yellow bold'
symbol = '*'
shell = [ 'bash' ]
when = 'test -n "$(git status --porcelain)"'

[git_status]
format = '[$ahead_behind]($style)'
style = "yellow"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
