format = """
$character\
$directory\
$git_branch\
(${custom.tiny_git_status}$git_status )\
"""

add_newline = false

[directory]
style = "bold blue" # rose pine moon
# style = "bold cyan" # original
truncation_length=1

[character]
# optional symbol ♪
success_symbol = "[›](bold green)"
error_symbol = "[›](bold red)"
vimcmd_symbol = "[›](bold purple)"

[git_branch]
format = "[$branch]($style) "
style = "bold purple" # rose pine moon
#style = "bold blue" # original

[custom.tiny_git_status]
format = '[$symbol]($style)'
style = 'yellow bold'
symbol = '*'
shell = [ 'bash' ]
when = 'test -n "$(git status --porcelain)"'

[git_status]
format = '[$ahead_behind]($style)'
style = "yellow bold"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
