# Everforest (Dark Medium)
# Authors: CptPotato, basbebe

# Original Author:
# URL: https://github.com/sainnhe/everforest
# Filename: colors/everforest.vim
# Author: sainnhe
# Email: sainnhe@gmail.com
# License: MIT License

inherits = "everforest_dark"

# remove italics
"constant.builtin" = { fg = "purple" }
"comment" = { fg = "grey1" }
"variable.builtin" = { fg = "purple" }
"namespace" = { fg = "yellow" }
"attribute" = { fg = "purple" }
"markup.italic" = {}

#[palette]
#bg0 = "#2d353b" # original
#bg0 = "#30243d" # noctis viola
#bg0 = "#323140" # average of both
