theme = "ferra_renew" # rose_pine_moon everforest_dark monokai_pro_ristretto

[editor]
# cursorline = true
auto-completion = false
auto-format = false
color-modes = true
line-number = "relative"
mouse = false
rulers = [80]
shell = ["fish", "-c"]
true-color = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.soft-wrap]
enable = true

[editor.lsp]
auto-signature-help = false

[keys.normal.space]
c = "toggle_comments"

[keys.normal]
X = "extend_line_above"
esc = ["collapse_selection", "keep_primary_selection"]
"C-c" = ["collapse_selection", "keep_primary_selection"]
"$" = "goto_line_end"
0 = "goto_line_start"
D = ["collapse_selection", "extend_to_line_end", "yank", "flip_selections", "delete_selection"]
G = "goto_file_end"

[keys.insert]
"C-c" = ["normal_mode", "collapse_selection", "keep_primary_selection"]

[keys.select]
"C-c" = ["normal_mode", "collapse_selection", "keep_primary_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
