# theme = "ayu_mirage"
# theme = "pop-dark"
# ayu_mirage colors dont seem right, heres some default ones i liked
# varua, penumbra+, everforest_dark, monokai_pro_ristretto
theme = "everforest_dark"

[editor]
true-color = true
color-modes = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# [keys.insert.j]
# k = "normal_mode" # Maps `jk` to exit insert mode
# j = "normal_mode" # Maps `jj` to exit insert mode

[keys.normal.space]
c = "toggle_comments"
"\\" = "toggle_comments"

[keys.normal]
"C-\\" = "toggle_comments" # broken on wsl
# {{ vim muscle memory
"C-c" = "no_op"
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
[keys.insert]
"C-c" = "normal_mode"
[keys.select]
"C-c" = "normal_mode"
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
# }}